// This file is auto-generated by @hey-api/openapi-ts

export type AccessTokenResponse = {
    tokenType?: string | null;
    accessToken: string;
    expiresIn: number;
    refreshToken: string;
};

export type AddConsignmentItemRequest = {
    name: string;
    description: string | null;
    price: number;
    size: string;
    brandId: number;
    color: string | null;
    tagIds: Array<number>;
};

export type BrandResponse = {
    id: number;
    name: string;
};

export type ConsignmentDetailResponse = {
    id?: number;
    supplierId?: number;
    consignmentDate?: string;
    items?: Array<ConsignmentItemResponse>;
};

export type ConsignmentItemResponse = {
    id?: number;
    name?: string;
    identificationNumber?: string;
    status?: unknown;
    evaluatedValue?: number;
    size?: string;
    brandId?: number;
    color?: string | null;
    description?: string | null;
    tagIds?: Array<number>;
};

export type ConsignmentSearchResult = {
    id?: number;
    consignmentDate?: string;
    supplierName: string;
    totalItems?: number;
};

export type ConsignmentSupplierEntity = {
    name: string;
    email: string;
    phoneNumber: string;
    initial: string;
    commissionPercentageInCash?: number;
    commissionPercentageInProducts?: number;
    address?: string | null;
    isDeleted?: boolean;
    deletedBy?: string | null;
    deletedOn?: string | null;
    id?: number;
    createdBy?: string;
    createdOn?: string;
    updatedOn?: string | null;
    updatedBy?: string | null;
};

export type ConsignmentSupplierResponse = {
    id?: number;
    name?: string;
    email?: string;
    phoneNumber?: string;
    address?: string;
    initials?: string;
    commissionPercentageInCash?: number;
    commissionPercentageInProducts?: number;
};

export type CreateConsignmentItem = {
    name: string;
    description: string | null;
    price: number;
    size: string;
    brandId?: number;
    tagIds?: Array<number>;
    color?: string | null;
};

export type CreateConsignmentRequest = {
    supplierId: number;
    consignmentDate: string;
};

export type CreateConsignmentSupplierRequest = {
    name: string;
    email: string;
    initial: string;
    phoneNumber: string;
    address?: string | null;
    commissionPercentageInCash?: number;
    commissionPercentageInProducts?: number;
};

export type ForgotPasswordRequest = {
    email: string;
};

export type HttpValidationProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type InfoRequest = {
    newEmail?: string | null;
    newPassword?: string | null;
    oldPassword?: string | null;
};

export type InfoResponse = {
    email: string;
    isEmailConfirmed: boolean;
};

export type LoginRequest = {
    email: string;
    password: string;
    twoFactorCode?: string | null;
    twoFactorRecoveryCode?: string | null;
};

export type PageWithTotalOfConsignmentSearchResult = {
    total: number;
    skip: number;
    take: number;
    items: Array<ConsignmentSearchResult>;
};

export type PageWithTotalOfConsignmentSupplierResponse = {
    total: number;
    skip: number;
    take: number;
    items: Array<ConsignmentSupplierResponse>;
};

export type RefreshRequest = {
    refreshToken: string;
};

export type RegisterRequest = {
    email: string;
    password: string;
};

export type ResendConfirmationEmailRequest = {
    email: string;
};

export type ResetPasswordRequest = {
    email: string;
    resetCode: string;
    newPassword: string;
};

export type TagResponse = {
    id: number;
    name: string;
};

export type TwoFactorRequest = {
    enable?: boolean | null;
    twoFactorCode?: string | null;
    resetSharedKey?: boolean;
    resetRecoveryCodes?: boolean;
    forgetMachine?: boolean;
};

export type TwoFactorResponse = {
    sharedKey: string;
    recoveryCodesLeft: number;
    recoveryCodes?: Array<string> | null;
    isTwoFactorEnabled: boolean;
    isMachineRemembered: boolean;
};

export type UpdateConsignmentItem = {
    id: number;
    name: string;
    description: string | null;
    price: number;
    size: string;
    brandId?: number;
    tagIds?: Array<number>;
    color?: string | null;
};

export type UpdateConsignmentItemRequest = {
    name: string;
    description: string | null;
    price: number;
    size: string;
    brandId: number;
    color: string | null;
    tagIds: Array<number>;
};

export type UpdateConsignmentRequest = {
    supplierId: number;
    consignmentDate: string;
    items: Array<UpdateConsignmentItem>;
    newItems: Array<CreateConsignmentItem>;
    deletedItemsIds: Array<number>;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostRegisterError = PostRegisterErrors[keyof PostRegisterErrors];

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: {
        useCookies?: boolean;
        useSessionCookies?: boolean;
    };
    url: '/login';
};

export type PostLoginResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type PostRefreshData = {
    body: RefreshRequest;
    path?: never;
    query?: never;
    url: '/refresh';
};

export type PostRefreshResponses = {
    /**
     * OK
     */
    200: AccessTokenResponse;
};

export type PostRefreshResponse = PostRefreshResponses[keyof PostRefreshResponses];

export type MapIdentityApiConfirmEmailData = {
    body?: never;
    path?: never;
    query: {
        userId: string;
        code: string;
        changedEmail?: string;
    };
    url: '/confirmEmail';
};

export type MapIdentityApiConfirmEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResendConfirmationEmailData = {
    body: ResendConfirmationEmailRequest;
    path?: never;
    query?: never;
    url: '/resendConfirmationEmail';
};

export type PostResendConfirmationEmailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostForgotPasswordData = {
    body: ForgotPasswordRequest;
    path?: never;
    query?: never;
    url: '/forgotPassword';
};

export type PostForgotPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostForgotPasswordError = PostForgotPasswordErrors[keyof PostForgotPasswordErrors];

export type PostForgotPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostResetPasswordData = {
    body: ResetPasswordRequest;
    path?: never;
    query?: never;
    url: '/resetPassword';
};

export type PostResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
};

export type PostResetPasswordError = PostResetPasswordErrors[keyof PostResetPasswordErrors];

export type PostResetPasswordResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostManage2FaData = {
    body: TwoFactorRequest;
    path?: never;
    query?: never;
    url: '/manage/2fa';
};

export type PostManage2FaErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManage2FaError = PostManage2FaErrors[keyof PostManage2FaErrors];

export type PostManage2FaResponses = {
    /**
     * OK
     */
    200: TwoFactorResponse;
};

export type PostManage2FaResponse = PostManage2FaResponses[keyof PostManage2FaResponses];

export type GetManageInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type GetManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetManageInfoError = GetManageInfoErrors[keyof GetManageInfoErrors];

export type GetManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type GetManageInfoResponse = GetManageInfoResponses[keyof GetManageInfoResponses];

export type PostManageInfoData = {
    body: InfoRequest;
    path?: never;
    query?: never;
    url: '/manage/info';
};

export type PostManageInfoErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostManageInfoError = PostManageInfoErrors[keyof PostManageInfoErrors];

export type PostManageInfoResponses = {
    /**
     * OK
     */
    200: InfoResponse;
};

export type PostManageInfoResponse = PostManageInfoResponses[keyof PostManageInfoResponses];

export type GetApiConsignmentsData = {
    body?: never;
    path?: never;
    query: {
        Skip: number;
        Take: number;
    };
    url: '/api/consignments';
};

export type GetApiConsignmentsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiConsignmentsResponses = {
    /**
     * OK
     */
    200: PageWithTotalOfConsignmentSearchResult;
};

export type GetApiConsignmentsResponse = GetApiConsignmentsResponses[keyof GetApiConsignmentsResponses];

export type PostApiConsignmentsData = {
    body: CreateConsignmentRequest;
    path?: never;
    query?: never;
    url: '/api/consignments';
};

export type PostApiConsignmentsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type PostApiConsignmentsResponses = {
    /**
     * Created
     */
    201: ConsignmentDetailResponse;
};

export type PostApiConsignmentsResponse = PostApiConsignmentsResponses[keyof PostApiConsignmentsResponses];

export type GetApiConsignmentsByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/consignments/{id}';
};

export type GetApiConsignmentsByIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiConsignmentsByIdResponses = {
    /**
     * OK
     */
    200: ConsignmentDetailResponse;
};

export type GetApiConsignmentsByIdResponse = GetApiConsignmentsByIdResponses[keyof GetApiConsignmentsByIdResponses];

export type PutApiConsignmentsByIdData = {
    body: UpdateConsignmentRequest;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/consignments/{id}';
};

export type PutApiConsignmentsByIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiConsignmentsByIdResponses = {
    /**
     * Accepted
     */
    202: unknown;
};

export type PostApiConsignmentsByConsignmentIdItemsData = {
    body: AddConsignmentItemRequest;
    path: {
        consignmentId: number;
    };
    query?: never;
    url: '/api/consignments/{consignmentId}/items';
};

export type PostApiConsignmentsByConsignmentIdItemsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PostApiConsignmentsByConsignmentIdItemsResponses = {
    /**
     * Created
     */
    201: ConsignmentItemResponse;
};

export type PostApiConsignmentsByConsignmentIdItemsResponse = PostApiConsignmentsByConsignmentIdItemsResponses[keyof PostApiConsignmentsByConsignmentIdItemsResponses];

export type DeleteApiConsignmentsByConsignmentIdItemsByItemIdData = {
    body?: never;
    path: {
        consignmentId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/consignments/{consignmentId}/items/{itemId}';
};

export type DeleteApiConsignmentsByConsignmentIdItemsByItemIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteApiConsignmentsByConsignmentIdItemsByItemIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiConsignmentsByConsignmentIdItemsByItemIdResponse = DeleteApiConsignmentsByConsignmentIdItemsByItemIdResponses[keyof DeleteApiConsignmentsByConsignmentIdItemsByItemIdResponses];

export type PutApiConsignmentsByConsignmentIdItemsByItemIdData = {
    body: UpdateConsignmentItemRequest;
    path: {
        consignmentId: number;
        itemId: number;
    };
    query?: never;
    url: '/api/consignments/{consignmentId}/items/{itemId}';
};

export type PutApiConsignmentsByConsignmentIdItemsByItemIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiConsignmentsByConsignmentIdItemsByItemIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiConsignmentsByConsignmentIdItemsByItemIdResponse = PutApiConsignmentsByConsignmentIdItemsByItemIdResponses[keyof PutApiConsignmentsByConsignmentIdItemsByItemIdResponses];

export type GetApiSuppliersData = {
    body?: never;
    path?: never;
    query: {
        Skip: number;
        Take: number;
    };
    url: '/api/suppliers';
};

export type GetApiSuppliersErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiSuppliersResponses = {
    /**
     * OK
     */
    200: PageWithTotalOfConsignmentSupplierResponse;
};

export type GetApiSuppliersResponse = GetApiSuppliersResponses[keyof GetApiSuppliersResponses];

export type PostApiSuppliersData = {
    body: CreateConsignmentSupplierRequest;
    path?: never;
    query?: never;
    url: '/api/suppliers';
};

export type PostApiSuppliersErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type PostApiSuppliersResponses = {
    /**
     * Created
     */
    201: ConsignmentSupplierResponse;
};

export type PostApiSuppliersResponse = PostApiSuppliersResponses[keyof PostApiSuppliersResponses];

export type DeleteApiSuppliersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}';
};

export type DeleteApiSuppliersByIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type DeleteApiSuppliersByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiSuppliersByIdResponse = DeleteApiSuppliersByIdResponses[keyof DeleteApiSuppliersByIdResponses];

export type GetApiSuppliersByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}';
};

export type GetApiSuppliersByIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetApiSuppliersByIdResponses = {
    /**
     * OK
     */
    200: ConsignmentSupplierResponse;
};

export type GetApiSuppliersByIdResponse = GetApiSuppliersByIdResponses[keyof GetApiSuppliersByIdResponses];

export type PutApiSuppliersByIdData = {
    body: ConsignmentSupplierEntity;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/suppliers/{id}';
};

export type PutApiSuppliersByIdErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutApiSuppliersByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PutApiSuppliersByIdResponse = PutApiSuppliersByIdResponses[keyof PutApiSuppliersByIdResponses];

export type GetApiSuppliersAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/suppliers/all';
};

export type GetApiSuppliersAllErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiSuppliersAllResponses = {
    /**
     * OK
     */
    200: Array<ConsignmentSupplierResponse>;
};

export type GetApiSuppliersAllResponse = GetApiSuppliersAllResponses[keyof GetApiSuppliersAllResponses];

export type GetApiUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/user/me';
};

export type GetApiUserMeErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiUserMeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiStoreBrandsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/store/brands';
};

export type GetApiStoreBrandsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiStoreBrandsResponses = {
    /**
     * OK
     */
    200: Array<BrandResponse>;
};

export type GetApiStoreBrandsResponse = GetApiStoreBrandsResponses[keyof GetApiStoreBrandsResponses];

export type GetApiStoreTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/store/tags';
};

export type GetApiStoreTagsErrors = {
    /**
     * Unauthorized - Invalid or missing authentication cookie
     */
    401: unknown;
    /**
     * Forbidden - Insufficient permissions
     */
    403: unknown;
};

export type GetApiStoreTagsResponses = {
    /**
     * OK
     */
    200: Array<TagResponse>;
};

export type GetApiStoreTagsResponse = GetApiStoreTagsResponses[keyof GetApiStoreTagsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:5026' | (string & {});
};